{
 "pytest_faulthandler": {
  "lineno": null,
  "symbols_in_volume": [],
  "type": "module"
 },
 "pytest_faulthandler._cancel_traceback_dump": {
  "lineno": 69,
  "symbols_in_volume": [
   "faulthandler.cancel_dump_traceback_later"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_addoption": {
  "lineno": 7,
  "symbols_in_volume": [],
  "type": "function"
 },
 "pytest_faulthandler.pytest_configure": {
  "lineno": 21,
  "symbols_in_volume": [
   "faulthandler.enable",
   "io.UnsupportedOperation",
   "os.dup",
   "os.fdopen",
   "sys.__stderr__.fileno",
   "sys.stderr.fileno"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_enter_pdb": {
  "lineno": 77,
  "symbols_in_volume": [
   "pytest.hookimpl"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_exception_interact": {
  "lineno": 84,
  "symbols_in_volume": [
   "pytest.hookimpl"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_runtest_protocol": {
  "lineno": 52,
  "symbols_in_volume": [
   "faulthandler.cancel_dump_traceback_later",
   "faulthandler.dump_traceback_later",
   "pytest.mark.hookwrapper"
  ],
  "type": "function"
 },
 "pytest_faulthandler.timeout_support_available": {
  "lineno": 43,
  "symbols_in_volume": [
   "faulthandler"
  ],
  "type": "function"
 }
}