{
 "pytest_faulthandler": {
  "lineno": null,
  "symbols_in_volume": [],
  "type": "module"
 },
 "pytest_faulthandler._cancel_traceback_dump": {
  "lineno": 71,
  "symbols_in_volume": [
   "faulthandler.cancel_dump_traceback_later"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_addoption": {
  "lineno": 9,
  "symbols_in_volume": [],
  "type": "function"
 },
 "pytest_faulthandler.pytest_configure": {
  "lineno": 23,
  "symbols_in_volume": [
   "faulthandler.enable",
   "io.UnsupportedOperation",
   "os.dup",
   "os.fdopen",
   "sys.__stderr__.fileno",
   "sys.stderr.fileno"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_enter_pdb": {
  "lineno": 79,
  "symbols_in_volume": [
   "pytest.hookimpl"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_exception_interact": {
  "lineno": 86,
  "symbols_in_volume": [
   "pytest.hookimpl"
  ],
  "type": "function"
 },
 "pytest_faulthandler.pytest_report_header": {
  "lineno": 39,
  "symbols_in_volume": [],
  "type": "function"
 },
 "pytest_faulthandler.pytest_runtest_protocol": {
  "lineno": 54,
  "symbols_in_volume": [
   "faulthandler.cancel_dump_traceback_later",
   "faulthandler.dump_traceback_later",
   "pytest.hookimpl"
  ],
  "type": "function"
 },
 "pytest_faulthandler.timeout_support_available": {
  "lineno": 45,
  "symbols_in_volume": [
   "faulthandler"
  ],
  "type": "function"
 }
}